### ISSUE TITLE
安装测试报错，app打包后打不开

### ISSUE THREAD

**Issue by mengchaoheng** [breezedeus/Pix2Text-Mac#8]
```sh
➜  ~ source ~/.bash_profile 
(base) ➜  ~ conda activate myenv                                      
(myenv) ➜  ~ which python
/Users/mch/opt/anaconda3/envs/myenv/bin/python
(myenv) ➜  ~ which python3
/Users/mch/opt/anaconda3/envs/myenv/bin/python3
(myenv) ➜  ~ which pip    
/Users/mch/opt/anaconda3/envs/myenv/bin/pip
(myenv) ➜  ~ which pip3
/Users/mch/opt/anaconda3/envs/myenv/bin/pip3
(myenv) ➜  ~ python --version
Python 3.11.10
(myenv) ➜  ~ cd Proj/Pix2Text-Mac 
(myenv) ➜  Pix2Text-Mac git:(main) p2t predict -l en,ch_sim --resized-shape 768 --file-type page -i assets/page.png -o output-page --save-debug-res output-debug-page
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /Users/mch/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/pix2text/doc_xl_layout/../../exp/ctdet_subfield/default
heads {'hm': 11, 'cls': 4, 'ftype': 3, 'wh': 8, 'hm_sub': 2, 'wh_sub': 8, 'reg': 2, 'reg_sub': 2}
[INFO 2024-10-22 15:45:13,093 load_model:36] loading model from local file: /Users/mch/.pix2text/1.1/layout-parser/DocXLayout_231012.pth 
[INFO 2024-10-22 15:45:13,108 _get_model:194] use model: /Users/mch/.cnocr/2.3/densenet_lite_136-gru/cnocr-v2.3-densenet_lite_136-gru-epoch=004-ft-model.onnx 
[INFO 2024-10-22 15:45:13,147 _assert_and_prepare_model_files:135] use model: /Users/mch/.cnstd/1.2/ppocr/ch_PP-OCRv3_det_infer.onnx 
2024-10-22 15:45:13.158085 [W:onnxruntime:, coreml_execution_provider.cc:107 GetCapability] CoreMLExecutionProvider::GetCapability, number of partitions supported by CoreML: 8 number of nodes in the graph: 232 number of nodes supported by CoreML: 216
Traceback (most recent call last):
  File "/Users/mch/opt/anaconda3/envs/myenv/bin/p2t", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/mch/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mch/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/mch/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mch/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mch/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mch/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/pix2text/cli.py", line 178, in predict
    p2t = Pix2Text.from_config(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mch/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/pix2text/pix_to_text.py", line 104, in from_config
    text_formula_ocr = TextFormulaOCR.from_config(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mch/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/pix2text/text_formula_ocr.py", line 144, in from_config
    mfd = MathFormulaDetector(**mfd_config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mch/opt/anaconda3/envs/myenv/lib/python3.11/site-packages/pix2text/formula_detector.py", line 57, in __init__
    raise FileNotFoundError(f'can not find available file in {model_path}')
FileNotFoundError: can not find available file in /Users/mch/.pix2text/1.1/mfd-onnx
(myenv) ➜  Pix2Text-Mac git:(main) 
```

**Comment by breezedeus** [comment]
这是模型没有自动下载吧。你先运行下面的命令。这个命令执行成功，再打包后打开 app。
```
p2t predict -l en,ch_sim --resized-shape 768 --file-type page -i assets/page.png -o output-page --save-debug-res output-debug-page
```

**Comment by mengchaoheng** [comment]
后来成功了，我也忘了做什么操作了。感谢作者 @breezedeus
